from microbit import *
暫停ms = sleep
LED燈=display
A鈕=button_a
B鈕=button_b
加速度=accelerometer
序列=uart
# LED捲動 = display.scroll
# LED設定像素 = display.set_pixel
# LED取得像素 = display.get_pixel
# LED清除 = display.clear
# LED顯示 = display.show
# A鈕按下嗎 = button_a.is_pressed
# A鈕按過嗎 = button_a.was_pressed
# A鈕取得次數 = button_a.get_presses
# B鈕按下嗎 = button_b.is_pressed
# B鈕按過嗎 = button_b.was_pressed
# B鈕取得次數 = button_b.get_presses
# 加速度x = accelerometer.get_x
# 加速度y = accelerometer.get_y
# 加速度z = accelerometer.get_z
# 加速度3軸 = accelerometer.get_values
# 加速度動作 = accelerometer.current_gesture
# 加速度計動作是 = accelerometer.is_gesture
# 序列初始化 = uart.init
# 序列寫入 = uart.write
# 序列有資料嗎 = uart.any
# 序列讀取 = uart.read